/// Flutter icons PokeType
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PokeType
///      fonts:
///       - asset: fonts/PokeType.ttf
///
///
///
import 'package:flutter/widgets.dart';

class PokeTypeIcons {
  PokeTypeIcons._();

  static const _kFontFam = 'PokeType';
  static const String? _kFontPkg = null;

  static const IconData ice =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData psychic =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData evil =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dragon =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fairy =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fly =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ghost =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData terastal =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
