//import 'package:poke_reco/data_structs/pokemon_state.dart';
import 'package:test/test.dart';
//import 'package:poke_reco/data_structs/poke_type.dart';

void main() {
  group('PokeType の単体テスト', () {
    //PokemonState defenderState = PokemonState();
    test('auto generated by tool', () {
      expect(true, true);
    });
  });
}