import 'package:flutter/material.dart';
import 'package:flutter_typeahead/flutter_typeahead.dart';

/// デフォルトでサジェストのボックスが角丸なTypeAheadField
class AppBaseTypeAheadField<T> extends TypeAheadField<T> {
  AppBaseTypeAheadField({
    required SuggestionsCallback<T> suggestionsCallback,
    required ItemBuilder<T> itemBuilder,
    required SuggestionSelectionCallback<T> onSuggestionSelected,
    TextFieldConfiguration textFieldConfiguration =
        const TextFieldConfiguration(),
    SuggestionsBoxDecoration? suggestionsBoxDecoration,
    Duration debounceDuration = const Duration(milliseconds: 300),
    SuggestionsBoxController? suggestionsBoxController,
    ScrollController? scrollController,
    WidgetBuilder? loadingBuilder,
    WidgetBuilder? noItemsFoundBuilder,
    ErrorBuilder? errorBuilder,
    AnimationTransitionBuilder? transitionBuilder,
    double animationStart = 0.25,
    Duration animationDuration = const Duration(milliseconds: 500),
    bool getImmediateSuggestions = false,
    double suggestionsBoxVerticalOffset = 5.0,
    AxisDirection direction = AxisDirection.down,
    bool hideOnLoading = false,
    bool hideOnEmpty = false,
    bool hideOnError = false,
    bool hideSuggestionsOnKeyboardHide = true,
    bool keepSuggestionsOnLoading = true,
    bool keepSuggestionsOnSuggestionSelected = false,
    bool autoFlipDirection = false,
    bool autoFlipListDirection = true,
    bool hideKeyboard = false,
    int minCharsForSuggestions = 0,
    void Function(bool)? onSuggestionsBoxToggle,
    bool hideKeyboardOnDrag = false,
    Key? key,
  }) : super(
          suggestionsCallback: suggestionsCallback,
          itemBuilder: itemBuilder,
          onSuggestionSelected: onSuggestionSelected,
          textFieldConfiguration: textFieldConfiguration,
          suggestionsBoxDecoration: suggestionsBoxDecoration ??
              SuggestionsBoxDecoration(borderRadius: BorderRadius.circular(8)),
          debounceDuration: debounceDuration,
          suggestionsBoxController: suggestionsBoxController,
          scrollController: scrollController,
          loadingBuilder: loadingBuilder,
          noItemsFoundBuilder: noItemsFoundBuilder,
          errorBuilder: errorBuilder,
          transitionBuilder: transitionBuilder,
          animationStart: animationStart,
          animationDuration: animationDuration,
          getImmediateSuggestions: getImmediateSuggestions,
          suggestionsBoxVerticalOffset: suggestionsBoxVerticalOffset,
          direction: direction,
          hideOnLoading: hideOnLoading,
          hideOnEmpty: hideOnEmpty,
          hideOnError: hideOnError,
          hideSuggestionsOnKeyboardHide: hideSuggestionsOnKeyboardHide,
          keepSuggestionsOnLoading: keepSuggestionsOnLoading,
          keepSuggestionsOnSuggestionSelected:
              keepSuggestionsOnSuggestionSelected,
          autoFlipDirection: autoFlipDirection,
          autoFlipListDirection: autoFlipListDirection,
          hideKeyboard: hideKeyboard,
          minCharsForSuggestions: minCharsForSuggestions,
          onSuggestionsBoxToggle: onSuggestionsBoxToggle,
          hideKeyboardOnDrag: hideKeyboardOnDrag,
          key: key,
        );
}
